services:
  app:
    image: node:18-alpine
    container_name: subx
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && node index.js"
    restart: always
    ports:
      - "3000:3000"